# Generated by Django 3.2.5 on 2021-07-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20210724_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='city_burmese',
            field=models.CharField(default='-', max_length=64),
        ),
    ]
